#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Run PR check with input

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'quay.io username'
        required: true
        type: string
      password:
        description: 'quay.io password'
        required: true
        type: string

env:
  PR_IMAGE_TAG: pr-test

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check all properties have description
      run: ./check_properties_description.sh
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Greetings
      run: echo "${{ github.ref_type }}"
    - name: Login to quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.event.inputs.username }}
        password: ${{ github.event.inputs.password }}
        registry: quay.io
    - name: Build with Maven
      run: mvn -B clean install -U -Pintegration
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_API_TOKEN }}
    - name: Build and push images
      run: ./build/build.sh --tag:${{ env.PR_IMAGE_TAG }} --build-platforms:linux/amd64,linux/ppc64le,linux/arm64 --builder:podman --push-image
